name: Build on PR and push to main branch
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'
          cache: 'pnpm' # Caches pnpm dependencies

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: pnpm generate
        
      - name: Build Command
        run: pnpm build
