name: Build on PR and push to main branch
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Install Node.js 22.12.0
        run: |
          curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node -v

      - name: Install pnpm 9.15.1
        run: |
          corepack enable
          corepack prepare pnpm@9.15.1 --activate
          pnpm -v

      - name: Install Dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: pnpm generate
        
      - name: Build Command
        run: pnpm build
